name: Probe probe-p2
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false
      deploy-docs:
        type: boolean
        required: false
        default: true
  release:
    types: [published]
permissions:
  contents: write
  actions: write

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
