name: Probe probe-p3
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false
      deploy-docs:
        type: boolean
        required: false
        default: true
  release:
    types: [published]
concurrency:
  group: probe
  cancel-in-progress: false

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
